name: Test & Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # See https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install

      - name: Test
        run: ./vendor/phpunit/phpunit/phpunit test
